# Generated by Django 2.1.7 on 2020-02-09 09:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('law', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LawCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('is_active', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('law', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='law.Law')),
            ],
            options={
                'verbose_name_plural': 'law category',
                'db_table': 'law_category',
            },
        ),
    ]
