# Generated by Django 2.1.7 on 2020-03-13 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('law', '0004_auto_20200313_1708'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lawinnercategory',
            old_name='law',
            new_name='sub_law',
        ),
        migrations.RemoveField(
            model_name='lawcategory',
            name='indictable_offence',
        ),
        migrations.RemoveField(
            model_name='lawcategory',
            name='summary_offence',
        ),
        migrations.AddField(
            model_name='lawinnercategory',
            name='indictable_offence',
            field=models.BooleanField(default=False, verbose_name='Indictable Offence'),
        ),
        migrations.AddField(
            model_name='lawinnercategory',
            name='summary_offence',
            field=models.BooleanField(default=False, verbose_name='Summary Offence'),
        ),
    ]
