# Generated by Django 2.1.7 on 2020-03-13 18:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('law', '0005_auto_20200313_1804'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lawinnercategory',
            old_name='sub_law',
            new_name='law',
        ),
    ]
