# Generated by Django 2.2 on 2020-03-21 02:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('law', '0007_lawinnercategory_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lawinnercategory',
            name='description',
        ),
        migrations.AddField(
            model_name='lawinnercategory',
            name='description_1',
            field=models.CharField(blank=True, default='Lorem ispum', max_length=1000, verbose_name='Description 1'),
        ),
        migrations.AddField(
            model_name='lawinnercategory',
            name='description_2',
            field=models.CharField(blank=True, default='Lorem ispum', max_length=1000, verbose_name='Description 2'),
        ),
    ]
