# Generated by Django 2.2 on 2020-03-21 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('law', '0008_auto_20200321_0233'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lawinnercategory',
            name='description_1',
            field=models.TextField(blank=True, max_length=1000, verbose_name='Description 1'),
        ),
        migrations.AlterField(
            model_name='lawinnercategory',
            name='description_2',
            field=models.TextField(blank=True, max_length=1000, verbose_name='Description 2'),
        ),
    ]
