# Generated by Django 2.1.7 on 2020-07-21 01:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('law', '0009_auto_20200321_0234'),
    ]

    operations = [
        migrations.AddField(
            model_name='lawinnercategory',
            name='a_f',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='lawinnercategory',
            name='appeal_court',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='lawinnercategory',
            name='keywords',
            field=models.TextField(blank=True, max_length=1000, verbose_name='SENTENCE by Magistrate'),
        ),
        migrations.AddField(
            model_name='lawinnercategory',
            name='m_f',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='lawinnercategory',
            name='max_setence',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='lawinnercategory',
            name='plead',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='lawinnercategory',
            name='sentence_by_magistrate',
            field=models.TextField(blank=True, max_length=1000, verbose_name='SENTENCE by Magistrate'),
        ),
    ]
