# Generated by Django 2.1.7 on 2020-07-21 01:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('law', '0011_auto_20200721_0130'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lawinnercategory',
            name='a_f',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Age Factor'),
        ),
        migrations.AlterField(
            model_name='lawinnercategory',
            name='appeal_court',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='lawinnercategory',
            name='keywords',
            field=models.TextField(blank=True, max_length=1000, verbose_name='keywords'),
        ),
        migrations.AlterField(
            model_name='lawinnercategory',
            name='m_f',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='M factor'),
        ),
        migrations.AlterField(
            model_name='lawinnercategory',
            name='max_setence',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='lawinnercategory',
            name='plead',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
