# Generated by Django 2.2 on 2020-03-15 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questionnaire', '0002_auto_20200315_1033'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionnaire',
            name='is_dropdown',
            field=models.BooleanField(default=False),
        ),
    ]
