# Generated by Django 2.2 on 2020-03-18 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questionnaire', '0005_auto_20200317_1738'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuestionnaireType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('q_type', models.CharField(max_length=250)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Question',
                'db_table': 'questionaire_type',
            },
        ),
        migrations.AlterField(
            model_name='quesanswer',
            name='answer',
            field=models.CharField(blank=True, default=False, max_length=350),
        ),
    ]
