# Generated by Django 2.2 on 2020-03-18 18:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('questionnaire', '0008_auto_20200318_1729'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='quesanswer',
            options={'verbose_name_plural': 'Questionnaire Options'},
        ),
        migrations.AlterField(
            model_name='quesanswer',
            name='ques',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='questionnaire.Questionnaire'),
        ),
    ]
