# Generated by Django 2.1.7 on 2020-03-24 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questionnaire', '0010_auto_20200324_1612'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionnaire',
            name='option',
            field=models.CharField(default=1, max_length=350),
            preserve_default=False,
        ),
    ]
