# Generated by Django 2.1.7 on 2020-03-24 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questionnaire', '0011_questionnaire_option'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionnaire',
            name='option',
            field=models.CharField(max_length=350, null=True),
        ),
        migrations.AlterField(
            model_name='questionnaire',
            name='option_type',
            field=models.CharField(choices=[('1', 'Radio'), ('2', 'Dropdown'), ('3', 'Spinner'), ('4', 'Text')], help_text='Option Types', max_length=50),
        ),
    ]
