# Generated by Django 2.1.7 on 2020-03-24 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questionnaire', '0012_auto_20200324_1702'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionnaire',
            name='option',
            field=models.CharField(blank=True, max_length=350, null=True),
        ),
    ]
