# Generated by Django 2.1.7 on 2020-03-28 06:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('law', '0009_auto_20200321_0234'),
        ('questionnaire', '0013_auto_20200324_1705'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionnaire',
            name='law_inner_category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='law.LawInnerCategory'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='questionnaire',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
