# Generated by Django 2.1.7 on 2020-03-29 15:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('questionnaire', '0015_auto_20200328_0740'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quesanswer',
            name='ques',
        ),
        migrations.AddField(
            model_name='quesanswer',
            name='device_id',
            field=models.CharField(max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='quesanswer',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='quesanswer',
            name='answer',
            field=models.TextField(blank=True, max_length=500),
        ),
    ]
