# Generated by Django 2.1.7 on 2020-04-26 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questionnaire', '0017_auto_20200417_1351'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserResponse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('respoonse_for', models.CharField(choices=[('need_a_atterney', 'need_a_atterney'), ('need_a_lawyer', 'need_a_lawyer'), ('need_bail', 'need_bail')], max_length=80)),
                ('name', models.CharField(max_length=120, null=True)),
                ('contact_info', models.CharField(max_length=120, null=True)),
                ('date', models.CharField(max_length=120, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Further Request',
                'db_table': 'User_requests',
            },
        ),
        migrations.AlterField(
            model_name='staticcontentapi',
            name='api_name',
            field=models.CharField(choices=[('need_atterney', 'need_atterney'), ('not_guilty', 'not_guilty'), ('judge_alone_trial', 'judge_alone_trial'), ('magistrate_court', 'magistrate_court'), ('to_jurrors', 'to_jurrors'), ('trial_by_jury', 'trial_by_jury'), ('sentence', 'sentence'), ('tip_information', 'tip_information')], max_length=80),
        ),
    ]
