# Generated by Django 2.1.7 on 2020-04-26 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questionnaire', '0018_auto_20200426_1437'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userresponse',
            options={'verbose_name_plural': 'User Requests for'},
        ),
        migrations.AddField(
            model_name='userresponse',
            name='device_id',
            field=models.CharField(max_length=120, null=True),
        ),
    ]
