# Generated by Django 2.1.7 on 2020-04-26 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questionnaire', '0019_auto_20200426_1451'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userresponse',
            name='respoonse_for',
        ),
        migrations.AddField(
            model_name='userresponse',
            name='response_for',
            field=models.CharField(choices=[('need_a_atterney', 'need_a_atterney'), ('need_a_lawyer', 'need_a_lawyer'), ('need_bail', 'need_bail')], max_length=80, null=True),
        ),
    ]
