# Generated by Django 2.1.7 on 2020-06-02 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questionnaire', '0020_auto_20200426_1455'),
    ]

    operations = [
        migrations.AddField(
            model_name='userresponse',
            name='appearance',
            field=models.CharField(max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='userresponse',
            name='offence',
            field=models.CharField(max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='userresponse',
            name='option',
            field=models.CharField(max_length=120, null=True),
        ),
    ]
