# Generated by Django 2.1.7 on 2020-06-08 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questionnaire', '0023_userresponse_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='userresponse',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
