# Generated by Django 2.1.7 on 2020-07-09 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questionnaire', '0025_auto_20200608_1459'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userresponse',
            name='status',
            field=models.BooleanField(default=''),
        ),
    ]
