# Generated by Django 2.1.7 on 2020-07-29 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questionnaire', '0027_auto_20200709_0519'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quesanswer',
            name='answer',
            field=models.TextField(blank=True, max_length=1500),
        ),
    ]
