# Generated by Django 2.1.7 on 2020-07-29 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questionnaire', '0028_auto_20200729_1744'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quesanswer',
            name='answer',
            field=models.TextField(blank=True, max_length=5000),
        ),
    ]
