# Generated by Django 2.1.7 on 2020-08-06 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questionnaire', '0029_auto_20200729_1745'),
    ]

    operations = [
        migrations.AddField(
            model_name='userresponse',
            name='comment',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
