# Generated by Django 2.1.7 on 2020-08-10 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questionnaire', '0031_ticket'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userresponse',
            name='status',
            field=models.CharField(default='', max_length=120, null=True),
        ),
    ]
