# Generated by Django 2.1.7 on 2020-08-18 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questionnaire', '0032_auto_20200810_1901'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ticket',
            old_name='first_name',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='last_name',
        ),
        migrations.AddField(
            model_name='ticket',
            name='challenge_status',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='ticket',
            name='idUrl',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='ticket',
            name='permit',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='ticket',
            name='ticket_url',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='ticket',
            name='total_amount',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='ticket',
            name='total_amount_USD',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
