# Generated by Django 2.1.7 on 2020-08-18 16:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('questionnaire', '0033_auto_20200818_1610'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ticket',
            old_name='ticket_id',
            new_name='ticket_order_id',
        ),
    ]
