# Generated by Django 2.1.7 on 2020-08-30 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questionnaire', '0034_auto_20200818_1635'),
    ]

    operations = [
        migrations.AddField(
            model_name='userresponse',
            name='needed_for_law',
            field=models.CharField(default=1, max_length=80),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userresponse',
            name='needed_for_options',
            field=models.CharField(default=1, max_length=800),
            preserve_default=False,
        ),
    ]
