# Generated by Django 2.1.7 on 2020-09-02 17:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('questionnaire', '0036_auto_20200902_1713'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userresponse',
            old_name='is_age_confirm',
            new_name='is_age_check',
        ),
        migrations.RenameField(
            model_name='userresponse',
            old_name='is_authorise',
            new_name='is_authorise_check',
        ),
    ]
