# Generated by Django 2.1.7 on 2020-11-16 07:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('questionnaire', '0037_auto_20200902_1731'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChallangeTicket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rep_status', models.CharField(default='', max_length=120, null=True)),
                ('rep_deadline', models.CharField(max_length=200, null=True)),
                ('notice_ref_number', models.CharField(default='', max_length=300, null=True)),
                ('vehicle_reg_number', models.CharField(default='', max_length=300, null=True)),
                ('driver_permit_number', models.CharField(default='', max_length=300, null=True)),
                ('notice_issue', models.CharField(default='', max_length=300, null=True)),
                ('reason', models.CharField(max_length=2000, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='challange_ticket_user', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Challange Tickets',
                'db_table': 'challange_tickets',
            },
        ),
    ]
