# Generated by Django 2.1.7 on 2021-01-24 15:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('questionnaire', '0041_challangeticket_get_response'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='challangeticket',
            name='get_response',
        ),
    ]
