# Generated by Django 2.1.7 on 2021-01-27 13:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('questionnaire', '0042_remove_challangeticket_get_response'),
    ]

    operations = [
        migrations.AddField(
            model_name='challangeticket',
            name='accept_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='challange_ticket_user_accept', to=settings.AUTH_USER_MODEL),
        ),
    ]
