# Generated by Django 2.1.7 on 2020-02-23 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20200220_1827'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='age_group',
            field=models.CharField(max_length=120, null=True, verbose_name='Age Group'),
        ),
        migrations.AlterField(
            model_name='user',
            name='mobile',
            field=models.CharField(max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(blank=True, default='user', max_length=200),
        ),
    ]
