# Generated by Django 2.1.7 on 2020-03-08 03:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_locations'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='locations',
            options={'verbose_name': 'User Location', 'verbose_name_plural': 'User Location'},
        ),
        migrations.AlterModelTable(
            name='locations',
            table='user_locations',
        ),
    ]
