# Generated by Django 2.1.7 on 2020-07-25 09:52

from django.db import migrations, models
import django.db.models.deletion
import django_extensions.db.fields
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_profileaccess_profilelocations'),
    ]

    operations = [
        migrations.CreateModel(
            name='Access',
            fields=[
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=200)),
                ('status', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Profile Access',
                'verbose_name_plural': 'Profile Access',
                'db_table': 'profile_access',
            },
        ),
        migrations.CreateModel(
            name='GeoLocations',
            fields=[
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=200)),
                ('status', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Locations',
                'verbose_name_plural': 'Locations',
                'db_table': 'user_geo_locations',
            },
        ),
        migrations.AlterModelOptions(
            name='locations',
            options={'verbose_name': 'User Device Location', 'verbose_name_plural': 'User Device Location'},
        ),
        migrations.AlterModelOptions(
            name='profileaccess',
            options={'verbose_name': 'User Profile Access', 'verbose_name_plural': 'User Profile Access'},
        ),
        migrations.AlterModelOptions(
            name='profilelocations',
            options={'verbose_name': 'User Profile Location', 'verbose_name_plural': 'User Profile Location'},
        ),
        migrations.RemoveField(
            model_name='profileaccess',
            name='name',
        ),
        migrations.RemoveField(
            model_name='profilelocations',
            name='name',
        ),
        migrations.AddField(
            model_name='profileaccess',
            name='access',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.Access'),
        ),
        migrations.AddField(
            model_name='profilelocations',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.GeoLocations'),
        ),
    ]
