# Generated by Django 2.1.7 on 2020-07-25 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0015_auto_20200725_0952'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='geolocations',
            options={'verbose_name': 'App Locations', 'verbose_name_plural': 'App Locations'},
        ),
        migrations.AddField(
            model_name='user',
            name='user_access',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='user_locations',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
