# Generated by Django 2.1.7 on 2020-07-25 15:47

from django.db import migrations, models
import django_extensions.db.fields
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0016_auto_20200725_1022'),
    ]

    operations = [
        migrations.CreateModel(
            name='AreaOfInterest',
            fields=[
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=200)),
                ('status', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Area Of Interest',
                'verbose_name_plural': 'Area Of Interest',
                'db_table': 'area_of_interest',
            },
        ),
        migrations.CreateModel(
            name='CourtPreference',
            fields=[
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=200)),
                ('status', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Court Preference',
                'verbose_name_plural': 'Court Preference',
                'db_table': 'court_preference',
            },
        ),
        migrations.AddField(
            model_name='user',
            name='area_of_interest',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='bar_number',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='court_preference',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='court_preference1',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='year_of_practise',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
