# Generated by Django 2.1.7 on 2020-07-27 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0019_areaofinterest_courtpreference'),
    ]

    operations = [
        migrations.CreateModel(
            name='Access1',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200)),
                ('status', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Profile Access',
                'verbose_name_plural': 'Profile Access',
                'db_table': 'user_profile_access1',
            },
        ),
        migrations.CreateModel(
            name='GeoLocations1',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200)),
                ('status', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'App Locations',
                'verbose_name_plural': 'App Locations',
                'db_table': 'user_geo_location',
            },
        ),
        migrations.AlterModelOptions(
            name='geolocations',
            options={},
        ),
        migrations.AlterModelOptions(
            name='profilelocations',
            options={},
        ),
        migrations.AlterField(
            model_name='user',
            name='mobile',
            field=models.CharField(max_length=200, null=True, unique=True),
        ),
    ]
