# Generated by Django 2.1.7 on 2020-11-21 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0020_auto_20200727_1612'),
    ]

    operations = [
        migrations.CreateModel(
            name='WiPayPayment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(blank=True, max_length=200)),
                ('total', models.CharField(blank=True, max_length=200)),
                ('email', models.CharField(blank=True, max_length=200)),
                ('name', models.CharField(blank=True, max_length=200)),
                ('order_id', models.CharField(blank=True, max_length=200)),
                ('return_url', models.CharField(blank=True, max_length=200)),
                ('status', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Payments',
                'verbose_name_plural': 'Payments',
                'db_table': 'wipay_payment',
            },
        ),
        migrations.CreateModel(
            name='AttorneyUser',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
            },
            bases=('users.user',),
        ),
        migrations.CreateModel(
            name='JudgeUser',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
            },
            bases=('users.user',),
        ),
    ]
