# Generated by Django 2.1.7 on 2020-11-21 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0021_attorneyuser_judgeuser_wipaypayment'),
    ]

    operations = [
        migrations.AddField(
            model_name='wipaypayment',
            name='date',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='wipaypayment',
            name='order_hash',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='wipaypayment',
            name='reasonCode',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='wipaypayment',
            name='reasonDescription',
            field=models.CharField(blank=True, max_length=2000),
        ),
        migrations.AddField(
            model_name='wipaypayment',
            name='responseCode',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
